from app.models import db, Author, environment, SCHEMA
from sqlalchemy.sql import text


def seed_authors():
    first = Author(name="J.R.R. Tolkien")
    second = Author(name="J.K. Rowling")
    third = Author(name="George R.R. Martin")
    fourth = Author(name="Brandon Sanderson")
    fifth = Author(name="Patrick Rothfuss")
    sixth = Author(name="Terry Pratchett")
    seventh = Author(name="Robert Jordan")
    eigth = Author(name="Terry Goodkind")
    ninth = Author(name="Stephen King")
    tenth = Author(name="Robert Ludlum")
    eleventh = Author(name="Fonda Lee")
    twelfth = Author(name="N.K. Jemisin")
    thirteenth = Author(name="Terry Brooks")
    fourteenth = Author(name="David Eddings")
    fifteenth = Author(name="Raymond E. Feist")
    sixteenth = Author(name="Terry Goodkind")
    seventeenth = Author(name="Joe Abercrombie")
    eighteenth = Author(name="Brent Weeks")
    nineteenth = Author(name="Jim Butcher")
    twentieth = Author(name="Scott Lynch")
    twentyfirst = Author(name="Robin Hobb")
    twentysecond = Author(name="Steven Erikson")
    twentythird = Author(name="Mark Lawrence")
    twentyfourth = Author(name="Peter V. Brett")
    twentyfifth = Author(name="Brian Staveley")
    twentysixth = Author(name="Daniel Polansky")
    twentyseventh = Author(name="Michael J. Sullivan")
    twentyeighth = Author(name="Anthony Ryan")
    twentyninth = Author(name="Pierce Brown")
    thirtieth = Author(name="Peter F. Hamilton")
    thirtyfirst = Author(name="Frank Herbert")
    thirtysecond = Author(name="Isaac Asimov")
    thirtythird = Author(name="Arthur C. Clarke")
    thirtyfourth = Author(name="Will Wight")
    thirtyfifth = Author(name="Andrew Rowe")
    thirtysixth = Author(name="Martha Wells")
    thirtyseventh = Author(name="Ursula K. Le Guin")
    thirtyeighth = Author(name="Tamsyn Muir")
    thirtyninth = Author(name="Katherine Addison")
    fourtieth = Author(name="Nnedi Okorafor")
    fortyfirst = Author(name="Andrzej Sapkowski")
    fortysecond = Author(name="Leigh Bardugo")
    fortythird = Author(name="Susanna Clarke")
    fortyfourth = Author(name="Naomi Novik")
    fortyfifth = Author(name="Lev Grossman")
    fortysixth = Author(name="Erin Morgenstern")
    fortyseventh = Author(name="V.E. Schwab")
    fortyeighth = Author(name="Holly Black")
    fortyninth = Author(name="Cassandra Clare")
    fiftieth = Author(name="Sarah J. Maas")
    fiftyfirst = Author(name="Victoria Aveyard")
    fiftysecond = Author(name="Marie Lu")
    fiftythird = Author(name="Kiera Cass")
    fiftyfourth = Author(name="Philip Pullman")
    fiftyfifth = Author(name="Cornelia Funke")
    fiftysixth = Author(name="Rick Riordan")
    fiftyseventh = Author(name="C.S. Lewis")
    fiftyeighth = Author(name="Josiah Bancroft")
    fiftyninth = Author(name="R.F. Kuang")
    sixtieth = Author(name="S.A. Chakraborty")
    sixtyfirst = Author(name="R.J. Barker")
    sixtysecond = Author(name="Jenn Lyons")
    sixtythird = Author(name="Douglas Adams")
    sixtyfourth = Author(name="Neil Gaiman")
    sixtyfifth = Author(name="John Gwynne")
    sixtysixth = Author(name="David Gemmell")
    sixtyseventh = Author(name="Michael Moorcock")
    sixtyeighth = Author(name="Ray Bradbury")
    sixtyninth = Author(name="John Scalzi")
    seventieth = Author(name="Orson Scott Card")
    seventyfirst = Author(name="Anne McCaffrey")
    seventysecond = Author(name="Margaret Atwood")
    seventythird = Author(name="Lois McMaster Bujold")
    seventyfourth = Author(name="Katherine Addison")
    seventyfifth = Author(name="Nicholas Eames")
    seventysixth = Author(name="James Islington")
    seventyseventh = Author(name="Evan Winter")
    seventyeighth = Author(name="Arkady Martine")
    seventyninth = Author(name="Brian McClellan")
    eightieth = Author(name="Django Wexler")
    eightyfirst = Author(name="Tasha Suri")
    eightysecond = Author(name="Glen Cook")
    eightythird = Author(name="Steven Brust")
    eightyfourth = Author(name="Kentaro Miura")
    eightyfifth = Author(name="Hajime Isayama")
    eightysixth = Author(name="Seth Dickinson")
    eightyseventh = Author(name="Eiiichiro Oda")
    eightyeighth = Author(name="Kazue Kato")
    eightyninth = Author(name="Travis Baldree")
    ninetieth = Author(name="David Dalglish")
    ninetyfirst = Author(name="Guy Gavriel Kay")
    ninetysecond = Author(name="R.A. Salvatore")
    ninetythird = Author(name="Ed Greenwood")
    ninetyfourth = Author(name="Saladin Ahmed")
    ninetyfifth = Author(name="Michael R. Fletcher")
    ninetysixth = Author(name="Miles Cameron")
    ninetyseventh = Author(name="Peter Newman")
    ninetyeighth = Author(name="E.K. Johnston")
    ninetyninth = Author(name="Terry Mancour")
    hundredth = Author(name="Daniel Abraham")



    db.session.add_all([first, second, third, fourth, fifth, sixth, seventh, eigth])
    db.session.add_all([ninth, tenth, eleventh, twelfth, thirteenth, fourteenth, fifteenth, sixteenth])
    db.session.add_all([seventeenth, eighteenth, nineteenth, twentieth, twentyfirst, twentysecond, twentythird, twentyfourth])
    db.session.add_all([twentyfifth, twentysixth, twentyseventh, twentyeighth, twentyninth, thirtieth, thirtyfirst, thirtysecond, thirtythird])
    db.session.add_all([thirtyfourth, thirtyfifth, thirtysixth, thirtyseventh, thirtyeighth, thirtyninth, fourtieth, fortyfirst])
    db.session.add_all([fortysecond, fortythird, fortyfourth, fortyfifth, fortysixth, fortyseventh, fortyeighth, fortyninth])
    db.session.add_all([fiftieth, fiftyfirst, fiftysecond, fiftythird, fiftyfourth, fiftyfifth, fiftysixth, fiftyseventh])
    db.session.add_all([fiftyeighth, fiftyninth, sixtieth, sixtyfirst, sixtysecond, sixtythird, sixtyfourth, sixtyfifth])
    db.session.add_all([sixtysixth, sixtyseventh, sixtyeighth, sixtyninth, seventieth, seventyfirst, seventysecond, seventythird])
    db.session.add_all([seventyfourth, seventyfifth, seventysixth, seventyseventh, seventyeighth, seventyninth, eightieth, eightyfirst])
    db.session.add_all([eightysecond, eightythird, eightyfourth, eightyfifth, eightysixth, eightyseventh, eightyeighth, eightyninth])
    db.session.add_all([ninetieth, ninetyfirst, ninetysecond, ninetythird, ninetyfourth, ninetyfifth, ninetysixth, ninetyseventh])
    db.session.add_all([ninetyeighth, ninetyninth, hundredth])
    db.session.commit()

def undo_authors():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.authors RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM authors"))

    db.session.commit()
