from app.models import db, Recommendation, environment, SCHEMA
from sqlalchemy.sql import text


def seed_recommendations():
    recommendation1 = Recommendation()
    recommendation2 = Recommendation()
    recommendation3 = Recommendation()
    recommendation4 = Recommendation()
    recommendation5 = Recommendation()
    recommendation6 = Recommendation()
    recommendation7 = Recommendation()
    recommendation8 = Recommendation()
    recommendation9 = Recommendation()
    recommendation10 = Recommendation()
    recommendation11 = Recommendation()
    recommendation12 = Recommendation()
    recommendation13 = Recommendation()
    recommendation14 = Recommendation()
    recommendation15 = Recommendation()
    recommendation16 = Recommendation()
    recommendation17 = Recommendation()
    recommendation18 = Recommendation()
    recommendation19 = Recommendation()
    recommendation20 = Recommendation()
    recommendation21 = Recommendation()
    recommendation22 = Recommendation()
    recommendation23 = Recommendation()
    recommendation24 = Recommendation()
    recommendation25 = Recommendation()
    recommendation26 = Recommendation()
    recommendation27 = Recommendation()
    recommendation28 = Recommendation()
    recommendation29 = Recommendation()
    recommendation30 = Recommendation()
    recommendation31 = Recommendation()
    recommendation32 = Recommendation()
    recommendation33 = Recommendation()
    recommendation34 = Recommendation()
    recommendation35 = Recommendation()
    recommendation36 = Recommendation()
    recommendation37 = Recommendation()
    recommendation38 = Recommendation()
    recommendation39 = Recommendation()
    recommendation40 = Recommendation()
    recommendation41 = Recommendation()
    recommendation42 = Recommendation()
    recommendation43 = Recommendation()
    recommendation44 = Recommendation()
    recommendation45 = Recommendation()
    recommendation46 = Recommendation()
    recommendation47 = Recommendation()
    recommendation48 = Recommendation()


    db.session.add_all([recommendation1, recommendation2, recommendation3, recommendation4, recommendation5, recommendation6, recommendation7, recommendation8, recommendation9, recommendation10, recommendation11, recommendation12, recommendation13, recommendation14, recommendation15, recommendation16, recommendation17, recommendation18, recommendation19, recommendation20, recommendation21, recommendation22, recommendation23, recommendation24, recommendation25, recommendation26, recommendation27, recommendation28, recommendation29, recommendation30, recommendation31, recommendation32, recommendation33, recommendation34, recommendation35, recommendation36, recommendation37, recommendation38, recommendation39, recommendation40, recommendation41, recommendation42, recommendation43, recommendation44, recommendation45, recommendation46, recommendation47, recommendation48])
    # db.session.add_all([recommendation1, recommendation2, recommendation3])
    db.session.commit()

def undo_recommendations():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.recommendations RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM recommendations"))

    db.session.commit()
